spring:
  application:
  name: office

  datasource:
    url: jdbc:postgresql://localhost:5432/vistula
    username: user
    password: 7878
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair: true
    out-of-order: true

jwt:
  secret: yO1Zm6nvzSnt2E2j9Y4WxRYb1d8Xq3tPL5jJwDlQ/3Y=
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

